//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Proyecto_progra_avanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCitas
    {
        public int IdCita { get; set; }
        public int IdMascota { get; set; }
        public int IdVeterinario { get; set; }
        public System.DateTime FechaCita { get; set; }
        public string Motivo { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual tbMascotas tbMascotas { get; set; }
        public virtual tbVeterinarios tbVeterinarios { get; set; }
    }
}
