//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_Proyecto_progra_avanzada.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInventario
    {
        public int IdInventario { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Categoria { get; set; }
        public int Stock { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public string Unidad { get; set; }
        public string Imagen { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public bool Estado { get; set; }
    }
}
